apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-ddpm-clip
spec:
  containers:
  - name: gpu-container
    image: pytorch/pytorch:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        cpu: "2"           # Limit CPU usage to 2 cores
        memory: "32Gi"     # Memory limit set to 32 GB
      requests:
        nvidia.com/gpu: 1  # Request 1 NVIDIA GPU
        cpu: "1"           # Request 1 core
        memory: "32Gi"     # Memory request 
    volumeMounts:
    - name: ddpm
      mountPath: /workspace/data  # Mount path for the persistent volume
  volumes:
  - name: ddpm
    persistentVolumeClaim:
      claimName: ddpm
